export { default as ServicesPage } from './ServicesPage'
export { default as PortfolioPage } from './PortfolioPage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as QuotePage } from './QuotePage'
export { default as HomePage } from './HomePage'
